service: notes-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  createNode:
    handler: handler.createNote
    events:
      - http:
          method: post
          path: notes
  updateNode:
    handler: handler.updateNote
    events:
      - http:
          method: put
          path: notes/{id}

  deleteNode:
    handler: handler.deleteNote
    events:
      - http:
          method: delete
          path: notes/{id}

  getAllNotes:
    handler: handler.getAllNotes
    events:
      - http:
          method: get
          path: notes

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
